### ISSUE TITLE
question : sunset time

### ISSUE THREAD

**Issue by kia1349** [MohamedAshraf701/prayers_times#1]
hi bro
good job
thanks in advance for this
i have a question:
how to get sunset time?
can you add this to your lib or if not , how can calculate it?

**Comment by MohamedAshraf701** [comment]
Thank you for your message and for using the Prayers Times package in Dart. I'm pleased to help with your query about obtaining the sunset time.

The sunset time is equivalent to the Maghrib salah (namaz) time. To get this time using the Prayers Times package, simply access the Maghrib prayer time.

If you'd like to delve deeper into the code or contribute, the package is open source on GitHub. If you have questions, please don't hesitate to ask for clarifications.

Thank you for your support!
