### ISSUE TITLE
prayerTimes?.ishaStartTime & prayerTimes?.ishaEndTime show in same day

### ISSUE THREAD

**Issue by Md-Tarikul-Islam-Juel** [MohamedAshraf701/prayers_times#2]
prayerTimes?.ishaStartTime : 2023-11-23 18:30:17.000+0600
prayerTimes?.ishaEndTime : 2023-11-23 04:59:13.000+0600 it should be 2023-11-24 04:59:13.000+0600

**Comment by MohamedAshraf701** [comment]
Thank you for your participation and the valuable information provided. We acknowledge that our mistake led to setting the Isha end time based on the date you provided, which coincidentally matched the Fajr start time.

Correction in the new update:
In our latest update, we have rectified this by setting the Isha end time to the next Fajr time, ensuring accurate representation.

Your feedback is invaluable, and we appreciate your understanding.

Thank you for your response.

**Comment by Md-Tarikul-Islam-Juel** [comment]
i solve that issue by add one day prayerTimes?.ishaEndTime.add(Duration(days: 1))

**Comment by MohamedAshraf701** [comment]
Thank you for your participation @Md-Tarikul-Islam-Juel , but I have fixed this issue as your solution will have 1 minute or second difference with it. Please check this in newer version of this package.

**Comment by Md-Tarikul-Islam-Juel** [comment]
Great
