### ISSUE TITLE
prayerTimes?.maghribStartTime & prayerTimes?.maghribEndTime

### ISSUE THREAD

**Issue by Md-Tarikul-Islam-Juel** [MohamedAshraf701/prayers_times#3]
prayerTimes?.maghribStartTime : 2023-11-24 17:11:05.000+0600
prayerTimes?.maghribEndTime : 2023-11-23 18:30:17.000+0600 it should be 2023-11-24 18:30:17.000+0600

i checked it on the 2023-11-24 date

**Comment by MohamedAshraf701** [comment]
I check that issue 
there was an mistake from my side while changes isha end time , by mistake i also change in magrib end time 
tommorow that will be fix and , new version will be available in pub.dev 
for now you can use isha start time inside of magrib end time , both same so 

thank you for your attention.

**Comment by Md-Tarikul-Islam-Juel** [comment]
i solve that issue just add one day with prayerTimes?.maghribEndTime.add(Duration(days: 1))

**Comment by MohamedAshraf701** [comment]
there is minor time different in this code 
`(prayerTimes?.maghribEndTime.add(Duration(days: 1)))`
it return previous day maghrib time (there is 1-2 min different or in seconds )
so use isha start time inside of your code 
`(prayerTimes?.maghribEndTime.add(Duration(days: 1)))`

**Comment by Md-Tarikul-Islam-Juel** [comment]
Sure,,, i also will update when you will update  the package

**Comment by MohamedAshraf701** [comment]
we fixed magrib time issue in new version ,
please check , and thank you for your attention,

have a great day .

**Comment by Md-Tarikul-Islam-Juel** [comment]
I checked it in version 0.0.6 and it is working fine, brother, keep it up
