### ISSUE TITLE
after night 12 isha time change , it show next day data before fajr

### ISSUE THREAD

**Issue by Md-Tarikul-Islam-Juel** [MohamedAshraf701/prayers_times#4]
prayerTimes.ishaStartTime : 2023-11-25 18:30:15.000+0600 it should be 2023-11-24 18:30:15.000+0600 
prayerTimes.ishaEndTime : 2023-11-26 05:01:00.000+0600 it shuld be 2023-11-25 05:01:00.000+0600

I checked it at 3 am 2023-11-25 but before Fajr, it should remain the same as the 2023-11-24 start time of Isha After Fajar I think it should be changed

**Comment by MohamedAshraf701** [comment]
it will be solve in next update ...

thank you
