### ISSUE TITLE
Question: prayerTimes.currentPrayer()

### ISSUE THREAD

**Issue by Md-Tarikul-Islam-Juel** [MohamedAshraf701/prayers_times#5]
at 4am i checked prayerTimes.currentPrayer() it returns  "ishabefore" string
what dost it mean can you explain ?

and can you please tell me all possible values of return of prayerTimes.currentPrayer()

**Comment by MohamedAshraf701** [comment]
there was an functionality which im working on it 
once it's complete , i will be inform you 
maybe it's complete on next update
